# Generated by Django 5.2.3 on 2025-07-02 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_myuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytodo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mytodo',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mytodo',
            name='task',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
