# Generated by Django 5.2.3 on 2025-07-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_mytodo_user_alter_mytodo_status_alter_mytodo_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytodo',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
